name: CI

on:
  - push
  - pull_request
  - workflow_dispatch
  
jobs:
  build:
    name: Build Dist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
      
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
            
      - name: Install depends
        run: npm install

      - name: Build dist
        run: npm run build
        
      - name: Upload dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
  
  publish:
        name: 'Publish to Github Pages'
        runs-on: ubuntu-latest
        needs: [build]
        
        steps:
          - uses: actions/checkout@v2
            
          - name: Download artifact
            uses: actions/download-artifact@v2
            with:
              name: dist
              path: dist/
              
          - name: Deploy to GitHub Pages
            # You may pin to the exact commit or the version.
            # uses: crazy-max/ghaction-github-pages@1510b11c0c2f843eafb8ff41b3da8c467c8d4a9f
            uses: crazy-max/ghaction-github-pages@v2.2.0
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              build_dir: dist/
              jekyll: false
              allow_empty_commit: false
              commit_message: ":rocket: Deploy GitHub Pages"

    
      
